## @brief This file part of NXP bootloader testing script named nxpbl.py
##
## Reference https://docs.python.org/3/tutorial/modules.html



MCUBOOT_BOOTLOADER_START_BYTE = 0x5A


MCUBOOT_FRAMING_PACKET_TYPE__ACK            = 0xA1
MCUBOOT_FRAMING_PACKET_TYPE__NAK            = 0xA2
MCUBOOT_FRAMING_PACKET_TYPE__ACK_ABORT      = 0xA3
MCUBOOT_FRAMING_PACKET_TYPE__COMMAND        = 0xA4
MCUBOOT_FRAMING_PACKET_TYPE__DATA           = 0xA5
MCUBOOT_FRAMING_PACKET_TYPE__PING           = 0xA6
MCUBOOT_FRAMING_PACKET_TYPE__PING_RESPONSE  = 0xA7



# MCUBoot command tags, MCUBOOTRM.pdf table 4-9, page 36:
MCUBOOT_COMMAND_TAG__FLASH_ERASE_ALL          = 0x01
MCUBOOT_COMMAND_TAG__FLASH_ERASE_REGION       = 0x02
MCUBOOT_COMMAND_TAG__READ_MEMORY              = 0x03
MCUBOOT_COMMAND_TAG__WRITE_MEMORY             = 0x04
MCUBOOT_COMMAND_TAG__FILL_MEMORY              = 0x05
MCUBOOT_COMMAND_TAG__FLASH_SECURITY_DISABLE   = 0x06
MCUBOOT_COMMAND_TAG__GET_PROPERTY             = 0x07
MCUBOOT_COMMAND_TAG__RESERVED                 = 0x08

MCUBOOT_COMMAND_TAG__EXECUTE                  = 0x09
MCUBOOT_COMMAND_TAG__CALL                     = 0x0A
MCUBOOT_COMMAND_TAG__RESET                    = 0x0B
MCUBOOT_COMMAND_TAG__SET_PROPERTY             = 0x0C
MCUBOOT_COMMAND_TAG__FLASH_ERASE_ALL_UNSECURE = 0x0D
MCUBOOT_COMMAND_TAG__FLASH_PROGRAM_ONCE       = 0x0E
MCUBOOT_COMMAND_TAG__FLASH_READ_ONCE          = 0x0F
MCUBOOT_COMMAND_TAG__FLASH_READ_RESOURCE      = 0x10

MCUBOOT_COMMAND_TAG__CONFIGURE_QUAD_SPI       = 0x11
MCUBOOT_COMMAND_TAG__RELIABLE_UPDATE          = 0x12
MCUBOOT_COMMAND_TAG__FLASH_READ_RESOURCE



#NXP_RESPONSE_TAG__
MCUBOOT_RESPONSE_TAG__GENERIC              = 0xA0
MCUBOOT_RESPONSE_TAG__GET_PROPERTY         = 0xA7
MCUBOOT_RESPONSE_TAG__READ_MEMORY          = 0xA3
MCUBOOT_RESPONSE_TAG__FLASH_READ_ONCE      = 0xAF
MCUBOOT_RESPONSE_TAG__FLASH_READ_RESOURCE  = 0xB0



def function_as_placeholder():
    print("trivial function for included python file holding NXP bootloader constants.")

